### ISSUE TITLE
Automatic conversion to PNG

### ISSUE THREAD

**Issue by slimooo** [yinkakun/gatsby-starter-glass#10]
Hello,

Great job, great design !

I don't understand one thing. Why do you convert your picture form JPG to PNG ? (https://gatsbyglass.netlify.app/about) 

How it's possible to disable it ? Or to convert images to webp format ?

Thank you

**Comment by yinkakun** [comment]
This is the default behaviour of `gatsby-plugin-sharp`, You can learn to customise it [here](https://www.gatsbyjs.com/plugins/gatsby-plugin-sharp)
