### ISSUE TITLE
Feature Request: Internationalization

### ISSUE THREAD

**Issue by 0xferit** [yinkakun/gatsby-starter-glass#4]
Great design, I loved it and forked it already.

But it would be really nice if it was supporting internationalization. If you consider doing visual design work of internationalization, I can contribute by implementing the logic, if you need a hand.

**Comment by yinkakun** [comment]
Thanks, @ferittuncer. I think internationalization would be a great enhancement for the project.
My concern is how this would fit in with Netlify CMS.
I'm sorry for the late response.

**Comment by 0xferit** [comment]
Quick Google search yielded me this: https://medium.com/@ponchique/dead-simple-internationalization-with-gatsby-netlify-cms-d66dc4ecdac4

Seems doable.
