### ISSUE TITLE
URL color not changing even on global styles? 

### ISSUE THREAD

**Issue by mapoztate** [yinkakun/gatsby-starter-glass#6]
After changing the colors on the global-styles.js file, most of the links change color to the font like this: 

![image](https://user-images.githubusercontent.com/71365470/118348950-74425b80-b502-11eb-99d6-105162236255.png)

But for certain pages, such as tags.js and the contact page, they do not change color. How would I implement this change? 

![image](https://user-images.githubusercontent.com/71365470/118348968-91772a00-b502-11eb-8e4d-896bb53b0be9.png)
![image](https://user-images.githubusercontent.com/71365470/118348978-9c31bf00-b502-11eb-9f79-4982bdcae2d0.png)

I cannot find where to change the colors of these links. Even changing after changing the heading color directly where the text is at does not change the color of the hyperlink.

**Comment by yinkakun** [comment]
Hi, sorry for the late response, my bad.

The components are styled with styled-component and their styles are co-located with their respective component.

The anchor tag in `src/templates/contact-template.js` can be styled at [https://github.com/yinkakun/gatsby-starter-glass/blob/e6a012d6fefab7d6d772e6b6ebec0eb73faaa416/src/templates/contact-template.js#L135](https://github.com/yinkakun/gatsby-starter-glass/blob/e6a012d6fefab7d6d772e6b6ebec0eb73faaa416/src/templates/contact-template.js#L135
)

The anchor tag in `/src/pages/tags.js` is unstyled yet, you can import and style with `styled-component`.

If you need any more help, please let me know.
