### ISSUE TITLE
Posts not being placed in numeric tags

### ISSUE THREAD

**Issue by mapoztate** [yinkakun/gatsby-starter-glass#8]
This post has three tags: two that start with letters and one that starts with numbers.

![image](https://user-images.githubusercontent.com/71365470/120250737-0e5d1000-c234-11eb-8dc4-6f6c6dc15427.png)

Upon looking at all the tags in the blog, it shows that there is one post marked 2020.

![image](https://user-images.githubusercontent.com/71365470/120250729-07ce9880-c234-11eb-8726-e2e849c84f09.png)

When clicking 2020 however, it shows that there are no posts marked under 2020.

![image](https://user-images.githubusercontent.com/71365470/120250774-2896ee00-c234-11eb-9f03-11c9305cfcf2.png)

Does it not support tags that start with numbers, and if so, could you possibly add the functionality?

EDIT: This seems to be a graphql problem and I've developed a workaround to make the number be recognized as a string; however, I'd still like to know if a numeral value is possible to implement.

**Comment by yinkakun** [comment]
I just added posts with numeric tags and it works alright here, https://gatsbyglass.netlify.app/tags/2022
